name: flutter_hud
description: A clean and lightweight progress HUD to show a running asynchronous task for Flutter.
version: 0.3.0
homepage: https://github.com/eyro-labs/flutter_hud

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
