name: flutter_hud
description: A clean and lightweight progress HUD to show a running asynchronous task for Flutter.
version: 0.1.0
author: Eyro Labs <me@eyro.co.id>
homepage: https://github.com/eyro-labs/flutter_hud

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter